[META]
results_path = results/NDP_burgers/
data_path = data/
experiment_name = burgers_NDP

[TRAININGPARAMETERS]
report_every = 25
seed = [1,2,3,4,5]
model = 'NDP'
uncertainty_quantification = ['diffusion']
backbone = ["NDP"]
batch_size = [128]
eval_batch_size = [1024]
n_epochs = 5000
early_stopping = 150
init = 'default'
learning_rate = 0.0005
lr_schedule = 'no'
optimizer = 'adam'
gradient_clipping = 1
data_loader_pin_memory = False
data_loader_num_workers = [0]
distributed_training = False
alpha = 0.05
n_samples_uq = 100
weight_decay = 0.0
warmup_lr = 100
### Model Parameters
dropout = [0.0]
hidden_dim = [64]
n_layers = [4]
n_ndp_heads = 4
### Diffusion Parameters
n_timesteps = [50]
n_components = 3
beta_endpoints = [(0.001, 0.2)]
distributional_method = ["deterministic", "normal", "iDDPM"]
closed_form = False
concat_condition_diffusion = False
evaluate = True
x_T_sampling_method = ["standard"]
conditional_free_guidance_training = False
ddim_churn = [1.0]
noise_schedule = 'linear'
regressor = None
metrics_plots = False
loss_lambda = [0.000001]
loss = ["crps"]
n_val_samples = 10
n_train_samples = 10
batch_accumulation = 1
rank = 10
mvnormal_method = 'lora'
gamma = 5.0

[DATAPARAMETERS]
dataset_name = ['1D_Burgers']
downscaling_factor = 4
standardize = True
select_timesteps = "random"
temporal_downscaling_factor = 2
