[META]
results_path = results/NDP_energy/
data_path = data/
experiment_name = energy_NDP

[TRAININGPARAMETERS]
report_every = 50
seed = [1234]
model = 'MLP'
uncertainty_quantification = ['diffusion']
backbone = ["NDP"]
batch_size = 32
eval_batch_size = 16384
n_epochs = [5000]
early_stopping = 1000
init = 'default'
learning_rate = 0.001
lr_schedule = 'no'
optimizer = 'adam'
gradient_clipping = 1
data_loader_pin_memory = False
data_loader_num_workers = [0]
distributed_training = False
alpha = 0.05
n_samples_uq = 100
weight_decay = 0.0
### Model Parameters
dropout = [0.0]
hidden_dim = [64]
n_layers = [4]
n_ndp_heads = 4
### Diffusion Parameters
n_timesteps = [50]
n_components = 3
beta_endpoints = [(0.001, 0.35)]
distributional_method = ["deterministic"]
closed_form = False
concat_condition_diffusion = False
evaluate = True
x_T_sampling_method = ["standard"]
conditional_free_guidance_training = False
use_yarin_gal_loss = False
ddim_churn = [1.0]
noise_schedule = 'linear'
regressor = None
metrics_plots = False
loss_lambda = [0.000001]

[DATAPARAMETERS]
dataset_name = ['concrete']
yarin_gal_uci_split_indices = [0,1,2,3,4]
max_dataset_size = 1000
standardize = True
validation_ratio = 0.1
