[META]
results_path = results/
data_path = data/
experiment_name = NDP_T2M

[TRAININGPARAMETERS]
report_every = 50
seed = [1]
model = 'NDP'
uncertainty_quantification = ['diffusion']
backbone = ["NDP"]
batch_size = [16]
eval_batch_size = [16]
n_epochs = 2000
early_stopping = 300
init = 'default'
learning_rate = 0.0005
lr_schedule = 'step'
optimizer = 'adam'
gradient_clipping = 1
data_loader_pin_memory = False
data_loader_num_workers = [0]
distributed_training = False
alpha = 0.05
n_samples_uq = 100
weight_decay = 0.0
warmup_lr = 100
### Model Parameters
dropout = [0.0]
hidden_dim = [512]
n_layers = [4]
n_ndp_heads = 8
### Diffusion Parameters
n_timesteps = [50]
n_components = 3
beta_endpoints = [(0.001, 0.2)]
distributional_method = ["deterministic"]
closed_form = False
concat_condition_diffusion = False
evaluate = True
x_T_sampling_method = ["standard"]
conditional_free_guidance_training = False
ddim_churn = [1.0]
noise_schedule = 'linear'
regressor = None
metrics_plots = False
loss_lambda = [0.000001]
loss = ["crps"]
n_val_samples = 10
n_train_samples = 10
batch_accumulation = 2
rank = 10
mvnormal_method = 'lora'
gamma = 5.0

[DATAPARAMETERS]
dataset_name = ['WeatherBench']
downscaling_factor = 1
standardize = True

