!!python/object:argparse.Namespace
aux_optim: !!python/object:argparse.Namespace
  amsgrad: true
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.001
  optimizer: Adam
  weight_decay: 0.0
data: !!python/object:argparse.Namespace
  data_root: ./data/datasets/UCI_Datasets
  dataset: uci
  dir: kin8nm
  n_splits: 20
  normalize_x: true
  normalize_y: true
  num_workers: 0
  one_hot_encoding: false
diffusion: !!python/object:argparse.Namespace
  beta_end: 0.02
  beta_schedule: linear
  beta_start: 0.0001
  conditioning_signal: NN
  noise_prior: false
  nonlinear_guidance: !!python/object:argparse.Namespace
    apply_early_stopping: true
    delta: 0
    dropout_rate: 0.1
    hid_layers:
    - 100
    - 50
    joint_train: false
    logging_interval: 10
    n_pretrain_epochs: 300
    n_pretrain_max_epochs: 1000
    negative_slope: 0.01
    patience: 50
    pre_train: true
    train_ratio: 0.6
    use_batchnorm: false
  num_figs: 10
  timesteps: 1000
  vis_step: 100
model: !!python/object:argparse.Namespace
  cat_x: true
  cat_y_pred: true
  data_dim: 9
  ema: true
  ema_rate: 0.9999
  feature_dim: 128
  type: simple
  var_type: fixedlarge
  x_dim: 8
  y_dim: 1
  z_dim: 2
optim: !!python/object:argparse.Namespace
  amsgrad: true
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.001
  optimizer: Adam
  weight_decay: 0.0
sampling: !!python/object:argparse.Namespace
  batch_size: 32
  image_folder: sampling_image_samples
  last_only: true
  sampling_size: 1000
testing: !!python/object:argparse.Namespace
  PICP_range:
  - 2.5
  - 97.5
  batch_size: 64
  compute_metric_all_steps: true
  coverage_t: 0
  fig_size:
  - 8
  - 5
  image_folder: testing_image_samples
  last_only: true
  make_plot: false
  mean_t: 0
  n_bins: 10
  n_z_samples: 1000
  nll_t: 0
  plot_freq: 10
  plot_gen: false
  plot_true: false
  sampling_size: 1000
  squared_plot: false
  trimmed_mean_range:
  - 0.0
  - 100.0
training: !!python/object:argparse.Namespace
  batch_size: 64
  image_folder: training_image_samples
  logging_freq: 2000
  n_epochs: 5000
  n_iters: 100000
  snapshot_freq: 1000000000
  validation_freq: 20000
